### ISSUE TITLE
License of this project ?

### ISSUE THREAD

**Issue by Poussinou** [nandan-desai-extras/PrivacyBreacher#5]
Hi @databurn-in,

What's the license of this project?

If it's something open-source like the GNU GPL v3 license, we could try to add it to [F-Droid](https://f-droid.org/) after that, if you're ok.

**Comment by ypid** [comment]
Doesn’t it say that in the README? MIT, ref: https://github.com/databurn-in/PrivacyBreacher#license. Not machine readable and without license file so GitHub cannot extract it but the license is there. I would also like to see it in F-Droid :wink:

https://reuse.software/ might also be useful for machine readable license information.

**Comment by Poussinou** [comment]
@ypid That's right, I was looking for the license.md file...

So @databurn-in would it be ok for you to add it to F-Droid? I opened a RFP [here](https://gitlab.com/fdroid/rfp/-/issues/1495) for you.

**Comment by Poussinou** [comment]
@databurn-in Would it be possible to have [Fastlane structures](https://gitlab.com/snippets/1895688) in the app's repo?

**Comment by NandanDesai** [comment]
Hi @Poussinou. Sorry for the late reply. I'll go through your request.
